steps:
  # ==========================================
  # 1. BUILD & DEPLOY AUTH-SERVICE
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cucimobil-repo/auth-service:latest', './backend/auth-service']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cucimobil-repo/auth-service:latest']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'auth-service', 
           '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/cucimobil-repo/auth-service:latest', 
           '--region', 'us-central1', 
           '--allow-unauthenticated']

  # ==========================================
  # 2. BUILD & DEPLOY API-SERVICE
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cucimobil-repo/api-service:latest', './backend/api-service']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cucimobil-repo/api-service:latest']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'api-service', 
           '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/cucimobil-repo/api-service:latest', 
           '--region', 'us-central1', 
           '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY